fun main() {
    print("Student Enrollment No. : ")
    var sten: String? = readLine()
    print("Student Name : ")
    var stn: String? = readLine()
    print("Student Branch : ")
    var stbr: String? = readLine()
    print("Student Class : ")
    var stcl: String? = readLine()
    print("Student Batch : ")
    var stbt: String? = readLine()
    print("Student College Name : ")
    var stc: String? = readLine()
    print("Student University Name : ")
    var stun: String? = readLine()
    print("Student Age : ")
    var stage: String? = readLine()

    println("***************************************")
    println("Student's Details: ")
    println("Student Enrollment No. : $sten")
    println("Student Name : $stn")
    println("Student Branch : $stbr")
    println("Student Class : $stcl")
    println("Student Batch : $stbt")
    println("Student College Name : $stc")
    println("Student University Name : $stun")
    println("Student Age : $stage")
}